### ISSUE TITLE
Document format query parameter convention in public REST APIs

### ISSUE THREAD

**Issue by cmars** [snyk/sweater-comb#278]
We're favoring a `?format=` parameter for endpoints which support providing responses in different representations.

Need to document:
- What the `format` parameter means and how to use it according to intended purpose.
- How it affects responses w.r.t. different content types.

**Comment by ianlivingstone** [comment]
The other aspect here is potentially whether to accept the `accepts` header and how that changes things :)

**Comment by cmars** [comment]
Rough sketching:

* Endpoints MAY support multiple content type representations of a resource.
* Representations other than JSON API MUST be represented with a Content-Type: header in the response other than JSON API.
* The response schema for other content types MAY reference an external schema, but it is optional. These responses will not be automatically validated by middleware or infrastructure, and it is the service author's responsibility to implement the content type properly.
* Endpoints MAY allow clients to request a supported content type using one of the two methods:
  * `?format=format_name` where _format_name_ is an application-specific logical nickname for the content type (not necessarily the formal content type used in headers). This parameter type should be an enum and well-explained with OpenAPI documentation fields.
  * `Accept: content_type` where _content_type_ is an IANA or improvised media content type identfier.
* If both `?format=` and the Accept: header are provided:
  * The service MAY respond with HTTP 406, or
  * The service MAY ignore the `?format=` parameter and use the `Accept:` content type

Defaults for the `format` parameter / `Accept:` header, when not provided:
* If the resource has a JSON API representation, then `format` SHOULD be optional and JSON API is the default response when it is not provided.
* A JSON API content type MAY be provided in the `Accept:` header to explicitly request a JSON API response. If not provided, JSON API is the default. 

If `Accept:` is supported by a service, cached responses to requests MUST take this header into account. If this is not possible, then `Accept:` MUST be ignored or rejected with a 406.

Accept is a little bit of a rabbit hole...

**Comment by garethr** [comment]
This describes the logic if both `?format=` and `Accept` are provided, but not the case where both are supported but one is provided. Probably worth being explicit about this. My take is that that should be fine, and should return the requested format.

**Comment by jlourenc** [comment]
> If Accept: is supported by a service, cached responses to requests MUST take this header into account. If this is not possible, then Accept: MUST NOT be supported.

This scenario is supported by the HTTP caching spec via the HTTP response header `Vary`: https://datatracker.ietf.org/doc/html/rfc7234#section-4.1

**Comment by cmars** [comment]
Noting that when #284 lands, we'll need to follow up with rules to enforce the MUSTs.
