### ISSUE TITLE
Removing a resource breaks the linter

### ISSUE THREAD

**Issue by cmars** [snyk/sweater-comb#397]
If I remove a resource, `sweater-comb lint` fails. The comparison tries to diff against the `main` branch, finds the resource that was removed, and throws an error trying to find the file to compare in the filesystem.

This is what happens if the "repos" resource is removed from the go-service-sample, for example:

```
sweater-comb lint
no arguments given, defaulting to Vervet API project configuration
Linting API rest
Running bulk-compare with globs internal/rest/resources/**/[2-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]/spec.yaml
Found file internal/rest/resources/repos/2022-04-04/spec.yaml
ENOENT: no such file or directory, open 'internal/rest/resources/repos/2022-04-04/spec.yaml'
exit on error: Error: bulk-compare internal/rest/resources failed with exit code 1
    at ChildProcess.<anonymous> (/Users/c/Projects/go-service-sample/node_modules/@snyk/sweater-comb/build/lint.js:261:44)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
make: *** [common.mk:111: lint-openapi] Error 1
```

**Comment by cmars** [comment]
A workaround for this is to temporarily add the removed resource directory pattern to the resource `excludes:` in .vervet.yaml, but it would be nice if the underlying bulk-compare feature were able to deal with the missing content in the working copy, and recognize it as a deletion.

**Comment by gablaxian** [comment]
Fixed in Sweater Comb v2.x
