### ISSUE TITLE
[Optic CI] Required parameters should be allowed in new versions

### ISSUE THREAD

**Issue by cmars** [snyk/sweater-comb#65]
We don't want to allow required parameters to be added once a version has been introduced -- but we need to be able to introduce them initially.

<img width="232" alt="Screen Shot 2021-11-11 at 12 04 36 PM" src="https://user-images.githubusercontent.com/23741/141347742-9e1ad7cd-27b9-4c04-91bc-e2f31d276482.png">

When running `node_modules/.bin/ts-node src/index.ts compare --to end-end-tests/api-standards/resources/thing/2021-11-10/000-baseline.yaml --context '{"changeDate":"2021-11-11","changeResource":"thing","changeVersion":"2021-11-10"}'`

**Comment by cmars** [comment]
CC @acunniffe

**Comment by acunniffe** [comment]
@cmars -- ahhh this happens when you don't specify a from. It's triggering the changelog rules, even though technically, it's not really being added. We know how to handle this case -- thanks for the test data. Will get this passing

**Comment by cmars** [comment]
Fixed by #72
